Algoritmo "10repita"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/07/2025
Var
// Seção de Declarações das variáveis 
  cont:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

        

Fimalgoritmo