Algoritmo "parametros"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Procedimento que recebe dois parâmetros e exibe a soma
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/07/2025

Var
   x, y: inteiro

Procedimento Soma(A, B: inteiro)
inicio
    escreval("Recebi valor: ", A)
    escreval("Recebi valor: ", B)
    escreval("A soma é: ", A + B)
fimprocedimento

Inicio
   x <- 5
   y <- 6
   Soma(x, y)
Fimalgoritmo

