Algoritmo "pares_para"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/07/2025
Var
// Seção de Declarações das variáveis 
     c:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
        para C<- 0 ate 10 passo 1 faca
        digite

Fimalgoritmo