Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/07/2025
Var
// Seção de Declarações das variáveis 
A,B,C:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

           A <-2
           B <- 3
           C <- 5
           
           escreva (falso ou verdadeiro)
Fimalgoritmo